const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {CredentialCapture}=require('../app/credential-capture.cjs');const {Accounts}=require('../app/accounts.cjs');
const origin='https://github.com';
const base={version:1,origin,documentId:'form',path:'/signup'};
function setup(){const saved=[];let now=1000;const capture=new CredentialCapture({save:v=>{saved.push(v);return {saved:true}},now:()=>now});return {capture,saved,expire:()=>now+=16*60000};}
function candidate(c,more={},id='a'){c.observe(id,origin,{...base,kind:'candidate',username:'accepted',email:'person@example.test',password:'fixture-only-secret',intent:'signup',submitted:true,...more},{task:'Fixture task',taskId:id});}
function success(c,more={},id='a'){return c.observe(id,origin,{...base,documentId:'dashboard',path:'/',kind:'authenticated',username:'accepted',evidence:'github-user-login',...more});}
test('typing or submission alone never persists an account',()=>{const {capture:c,saved}=setup();candidate(c,{submitted:false});success(c);assert.equal(saved.length,0);candidate(c);assert.equal(saved.length,0);});
test('confirmed final identity saves username email password task once',()=>{const {capture:c,saved}=setup();candidate(c);success(c);success(c);assert.equal(saved.length,1);assert.equal(saved[0].email,'person@example.test');assert.equal(saved[0].task,'Fixture task');assert.equal(saved[0].source,'automatic');assert.equal(c.pending.size,0);});
test('rejected username cannot be persisted as an alternative account',()=>{const {capture:c,saved}=setup();candidate(c,{username:'taken'});success(c);assert.equal(saved.length,0);candidate(c,{username:'accepted',submitted:false});success(c);assert.equal(saved.length,0);candidate(c);success(c);assert.equal(saved[0].username,'accepted');});
test('wrong account and wrong email success signals are rejected',()=>{const {capture:c,saved}=setup();candidate(c);success(c,{username:'other'});success(c,{email:'other@example.test'});assert.equal(saved.length,0);});
test('an unrelated tab cannot confirm another tab credentials',()=>{const {capture:c,saved}=setup();candidate(c);success(c,{},'b');assert.equal(saved.length,0);});
test('linked verification child confirms exact identity and preserves manual consent context',()=>{const {capture:c,saved}=setup();candidate(c);c.observe('child',origin,{...base,documentId:'verified',path:'/',kind:'authenticated',username:'accepted',evidence:'github-user-login'},{parentTabId:'a'});assert.equal(saved.length,1);assert.equal(saved[0].taskId,'a');assert.notEqual(saved[0].agentCreated,true);});
test('linked verification child cannot save a rejected password or wrong identity',()=>{const {capture:c,saved}=setup();candidate(c);const confirm=username=>c.observe('child',origin,{...base,documentId:'verified',path:'/',kind:'authenticated',username,evidence:'github-user-login'},{parentTabId:'a'});confirm('different');assert.equal(saved.length,0);c.observe('a',origin,{...base,kind:'rejected'});confirm('accepted');assert.equal(saved.length,0);});
test('origin spoofing and expired candidates cannot save',()=>{const {capture:c,saved,expire}=setup();candidate(c,{origin:'https://other.test'});success(c);assert.equal(saved.length,0);candidate(c);expire();success(c);assert.equal(saved.length,0);});
test('incomplete and same-form success claims do not save',()=>{const {capture:c,saved}=setup();candidate(c);success(c,{documentId:'form',path:'/signup'});assert.equal(saved.length,0);success(c,{evidence:'logout-control'});assert.equal(saved.length,0);});
test('email-first multi-page login retains first step identifier',()=>{const {capture:c,saved}=setup();candidate(c,{username:'',password:'',submitted:true,email:'person@example.test',intent:'login'});c.observe('a',origin,{...base,documentId:'password-step',path:'/session',kind:'candidate',password:'fixture-next',submitted:true,intent:'login'});success(c);assert.equal(saved.length,1);assert.equal(saved[0].username,'accepted');assert.equal(saved[0].email,'person@example.test');});
test('clearing password and closing tab discard pending attempts',()=>{const {capture:c,saved}=setup();candidate(c);candidate(c,{password:'',submitted:false});success(c);assert.equal(saved.length,0);candidate(c);c.forget('a');success(c);assert.equal(saved.length,0);});
test('logout controls can confirm existing login but not a signup',()=>{const {capture:c,saved}=setup();candidate(c,{intent:'login'});success(c,{evidence:'logout-control',username:undefined});assert.equal(saved.length,1);});
test('already-authenticated forms never become credential attempts',()=>{const {capture:c,saved}=setup();candidate(c,{alreadyAuthenticated:true});success(c);assert.equal(saved.length,0);});
test('a rejected password or new login form prevents later session from saving it',()=>{const {capture:c,saved}=setup();candidate(c);c.observe('a',origin,{...base,kind:'rejected'});success(c);assert.equal(saved.length,0);candidate(c);c.observe('a',origin,{...base,documentId:'new-form',kind:'form'});success(c);assert.equal(saved.length,0);});
test('SSO fallback discards the previous attempted password',()=>{const {capture:c,saved}=setup();candidate(c);c.observe('a',origin,{...base,kind:'cancelled'});success(c);assert.equal(saved.length,0);assert.equal(c.pending.size,0);});
test('expiry sweep removes idle pending credentials from memory',()=>{const {capture:c,expire}=setup();candidate(c);expire();c.sweep();assert.equal(c.pending.size,0);});
test('email-only records update one saved account and retain default',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'spaces-account-unit-'));const store={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()};
 const a=new Accounts(path.join(dir,'fixture'),store);const first=a.save({site:origin,username:'accepted',email:'person@example.test',password:'fixture-a',status:'created'});a.setDefault(first.accountId);
 a.save({site:origin,email:'person@example.test',password:'fixture-b',status:'created'});assert.equal(a.list().length,1);assert.equal(a.list()[0].username,'accepted');assert.equal(a.list()[0].isDefault,true);assert.equal(a.list()[0].password,undefined);assert.equal(a.reveal(first.accountId).password,'fixture-b');
 assert.throws(()=>a.save({site:origin,username:'x',password:'secret',status:'pending'}));
 assert.throws(()=>a.save({site:origin,email:'person@example.test',password:'',status:'created'}));
});
