const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const {execFile}=require('node:child_process');
const BEGIN='<!-- agent-spaces:browser-default:start -->';const END='<!-- agent-spaces:browser-default:end -->';
const BLOCK=`${BEGIN}
## Agent Spaces workspace routing

Use the agent-browser MCP tools in Agent Spaces for all opening, navigation, and interaction with browser tabs by default. Create a tab for each independent task, use its returned tab ID, and respect ownership and manual-control pauses. Pass this browser preference and the assigned tab ID to any delegated worker.
Use browser_show_tab to show your owned working tab when the user wants to watch or inspect results. Avoid repeatedly switching tabs during background work.
For CAPTCHA or manual help, tell the user to finish in Agent Spaces and click Return to agent. Call browser_request_human, then browser_wait_for_resume repeatedly while waiting. Do not end the turn or require a chat reply. After resumed, inspect the current page and continue the original task without blindly replaying old actions.
Before logging in, use browser_get_account with the saved site origin. If the user names an account, pass username to select it explicitly without changing the default. A manually selected default account is used automatically. If multiple accounts match without a default, ask the user to choose in Agent Spaces Accounts and call browser_wait_for_account until answered, then retrieve the choice. Never guess which account to use. Keep retrieved credentials out of logs and replies.
After an action that may open a new tab, inspect returned popups and use browser_wait_for_popup with the prior popupCursor for delayed links. Continue verification in the returned owned child tab. Do not assume the original tab is the only result.
For account creation, call browser_record_account only after observing successful creation, with status created and the final accepted username and password. Never record rejected username attempts, failed signups, or incomplete verification. Keep credentials out of task labels and logs. Use browser_type_text after coordinate clicking fields inside cross-origin iframes.
Do not open or operate a personal browser, host browser, or in-app browser as a fallback. If Agent Spaces or its tools are unavailable, explain that Agent Spaces must be opened or Codex restarted to load the connector. An explicit user request to use a different browser or an existing named tab takes precedence over this default. This preference does not grant authorization for external actions or override higher-priority instructions.
${END}`;
function merge(text,enabled){const start=text.indexOf(BEGIN),end=text.indexOf(END);if((start<0)!==(end<0)||end<start)throw Error('The Agent Spaces instruction block is incomplete. Restore it before retrying.');const block=enabled?BLOCK:'';if(start>=0)return text.slice(0,start)+block+text.slice(end+END.length);return enabled?text+(text&&!text.endsWith('\n')?'\n':'')+block+'\n':text;}
function executable(name){for(const dir of (process.env.PATH||'').split(path.delimiter)){const p=path.join(dir,name);if(fs.existsSync(p))return p;}return null;}
function cliRunner(){const node=executable(process.platform==='win32'?'node.exe':'node');if(!node)throw Error('Node.js was not found. Install Node.js, then reopen Agent Spaces.');const js=path.join(process.env.APPDATA||'', 'npm','node_modules','@openai','codex','bin','codex.js');const binary=executable(process.platform==='win32'?'codex.exe':'codex');const command=fs.existsSync(js)?node:binary;if(!command)throw Error('Codex CLI was not found. Install Codex CLI, then reopen Agent Spaces.');return {node,run:args=>new Promise((resolve,reject)=>execFile(command,fs.existsSync(js)?[js,...args]:args,{windowsHide:true,timeout:20000,maxBuffer:1024*1024},(e,out)=>e?reject(Error('Codex connector setup failed. Check that Codex CLI is installed and writable.')):resolve(out)))};}
async function setup({root,enabled=true,codexHome=process.env.CODEX_HOME||path.join(os.homedir(),'.codex'),runner}={}){
 const override=path.join(codexHome,'AGENTS.override.md');const file=fs.existsSync(override)?override:path.join(codexHome,'AGENTS.md');
 let changed=false;
 if(enabled){const cli=runner||cliRunner();const args=[path.join(root,'browser-mcp.mjs')];let current;try{current=JSON.parse(await cli.run(['mcp','get','agent-browser','--json']))}catch{}
  if(current?.transport?.command!==cli.node||JSON.stringify(current?.transport?.args)!==JSON.stringify(args)||current.enabled===false){await cli.run(['mcp','add','agent-browser','--',cli.node,...args]);changed=true;}
 }
 fs.mkdirSync(codexHome,{recursive:true});const before=fs.existsSync(file)?fs.readFileSync(file,'utf8'):'';const after=merge(before,enabled);
 if(before!==after){if(fs.existsSync(file))fs.copyFileSync(file,file+'.agent-spaces-backup-'+Date.now());fs.writeFileSync(file,after);changed=true;}
 return {enabled,changed,instructionsFile:file,message:enabled?'Browser preference saved. Restart Codex if it is already open.':'Browser preference disabled. The connector remains available.'};
}
function writeInstructions({enabled=true,codexHome=process.env.CODEX_HOME||path.join(os.homedir(),'.codex')}={}){const override=path.join(codexHome,'AGENTS.override.md');const file=fs.existsSync(override)?override:path.join(codexHome,'AGENTS.md');const before=fs.existsSync(file)?fs.readFileSync(file,'utf8'):'';const after=merge(before,enabled);if(before!==after){fs.mkdirSync(codexHome,{recursive:true});if(fs.existsSync(file))fs.copyFileSync(file,file+'.agent-spaces-backup-'+Date.now());fs.writeFileSync(file,after);}return file;}
module.exports={setup,merge,BLOCK,writeInstructions};
