let accountVersion='';
let state={tabs:[],clients:[],events:[],selected:null,paused:false};let previewBusy=false,filtered=[];const ROW=44;
const $=id=>document.getElementById(id);
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),5500)}
async function invoke(action,args={}){try{return await window.spaces.invoke(action,args)}catch(e){toast(e.message.replace(/^Error invoking remote method.*?Error: /,''));}}
const make=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
for(const b of document.querySelectorAll('button[title]'))b.setAttribute('aria-label',b.title);
const halt=make('button','Halt input');halt.onclick=()=>invoke('halt',{id:state.selected});$('intervention').append(halt);
function status(t){return t.error?'Intervention required':t.loading?'Loading document':t.busy?`Executing: ${t.action}`:t.paused?'Manual control':t.ownerLabel?'Idle. Agent assigned':'Idle. Unassigned'}
function dot(t){return t.error?'error':t.busy||t.loading?'busy':t.owner?'ready':''}
function highlight(text){const f=document.createDocumentFragment();let p=0;const regex=/"([^"\\]|\\.)*"\s*:|"([^"\\]|\\.)*"|\b(true|false|null|\d+)\b/g;for(const m of text.matchAll(regex)){f.append(document.createTextNode(text.slice(p,m.index)),make('span',m[0],m[0].endsWith(':')?'json-key':'json-value'));p=m.index+m[0].length;}f.append(document.createTextNode(text.slice(p)));return f}
function renderLogs(){const v=$('logViewport');const first=Math.max(0,Math.floor(v.scrollTop/ROW)-4);const last=Math.min(filtered.length,first+Math.ceil(v.clientHeight/ROW)+9);$('logSpacer').style.height=`${filtered.length*ROW}px`;$('logRows').style.top=`${first*ROW}px`;$('logRows').replaceChildren();for(let i=first;i<last;i++){const e=filtered[i];const row=make('div',undefined,`log-row ${e.level||'info'}`);row.title=e.message;row.append(make('time',new Date(e.at).toLocaleTimeString([],{hour12:false})),make('span',(e.level||'info').toUpperCase(),'level'));const m=make('span',undefined,'message');m.append(highlight(e.message));row.append(m);$('logRows').append(row)}}
function updateLogs(){const query=$('logFilter').value.toLowerCase();const v=$('logViewport'),nearEnd=v.scrollHeight-v.scrollTop-v.clientHeight<70;filtered=state.events.filter(e=>e.message.toLowerCase().includes(query));$('logCount').textContent=filtered.length;renderLogs();if(nearEnd){v.scrollTop=v.scrollHeight;renderLogs()}}
function render(s){
 const chosenEngine=s.browserBackend||s.backend;$('switchEngine').value=chosenEngine;$('browserEngine').textContent=chosenEngine!==s.backend?'Restart AS to apply.':'Changing engines requires an AS restart.';
 const attention=s.attention||[];$('attentionAlert').hidden=!attention.length;if(attention.length){$('attentionTitle').textContent=attention[0].title;$('attentionMessage').textContent=attention[0].message;$('attentionCount').textContent=attention.length>1?attention.length+' requests need attention':'';$('attentionOpen').onclick=()=>invoke('openAttention',{id:attention[0].id});}
 if(s.pendingClose){const account=s.pendingClose.kind==='account';$('deleteTitle').textContent=account?'Delete saved account?':'Delete this tab?';$('deleteDescription').textContent=account?'This removes the saved login details from Agent Spaces. It does not delete the account on the website or sign out existing browser sessions.':'Unsaved work in this tab will be lost. Saved accounts and cookies will remain.';$('confirmDeleteHistory').hidden=account;$('confirmDelete').textContent=account?'Delete saved account':'Delete tab';$('deleteTabName').textContent=s.pendingClose.title;if(!$('deleteDialog').open)$('deleteDialog').showModal();}else if($('deleteDialog').open)$('deleteDialog').close();
 const c=s.codexStatus||{busy:true};$('codexStatus').hidden=!c.error;$('codexStatus').textContent=c.error?c.message:'';$('codexDetails').textContent='Opens agent browser work here by default. Codex may need a reload.';$('codexToggle').disabled=!!c.busy;$('codexToggle').textContent=c.busy?'Connecting…':c.error?'Retry setup':c.enabled?'On':'Off';$('codexToggle').setAttribute('role',c.error?'button':'switch');if(c.error)$('codexToggle').removeAttribute('aria-checked');else $('codexToggle').setAttribute('aria-checked',String(!!c.enabled));$('codexToggle').setAttribute('aria-label',c.error?'Retry Codex setup':'Use Agent Spaces for browser tasks');
 const previous=state.selected;state=s;renderSidebar(s);renderDialogs(s);renderAccounts(s);document.body.classList.remove('booting');document.body.classList.toggle('collapsed',!!s.collapsed);$('tabCount').textContent=s.tabs.length;$('cardCount').textContent=`${s.tabs.length} resources`;$('footerTabs').textContent=`${s.tabs.length} tabs`;
 const running=s.tabs.filter(t=>t.owner&&t.busy).length,assigned=s.tabs.filter(t=>t.owner&&!t.paused).length;$('connection').textContent=s.paused?(running?`Pausing browser · ${running} action(s) finishing`:'Browser agents paused'):running?`${running} browser action(s) running`:assigned?`${assigned} browser tab(s) assigned · idle`:'No browser work running';$('connection').title=`${s.clients.length} connected tool session(s). Connections are not running tasks.`;$('pauseAll').textContent=s.paused?'Resume browser agents':'Pause browser agents';$('pauseAll').title=s.paused?'Browser agents are paused across AS, including new tasks. Click to resume. This pause survives closing tabs and restarting AS.':'Pause browser agent actions across AS, including new tasks. An in-flight action may finish.';
 $('tabs').replaceChildren();$('cards').replaceChildren();
 for(const t of s.tabs){const b=make('button',undefined,`tab ${t.id===s.selected?'selected':''}`);b.append(make('span',undefined,`dot ${dot(t)}`));const copy=make('span',undefined,'tab-copy');copy.append(make('b',t.title),make('small',status(t)+' · '+(s.backend==='webview2'?'WebView2':'Electron')));b.append(copy);b.onclick=()=>invoke('select',{id:t.id});const row=make('div',undefined,'tab-row');const remove=make('button','×','tab-delete');remove.title='Delete tab';remove.setAttribute('aria-label','Delete tab: '+t.title);remove.disabled=!!t.busy;remove.onclick=()=>invoke('close',{id:t.id});const rename=make('button','✎','tab-delete');rename.title='Rename tab';rename.setAttribute('aria-label','Rename tab: '+t.title);rename.onclick=()=>invoke('rename',{id:t.id});b.append(make('span',s.backend==='webview2'?'Edge':'Electron','engine-badge'));row.append(b,rename,remove);$('tabs').append(row);const c=make('button',undefined,'card');const top=make('div',undefined,'card-top');top.append(make('span',s.backend==='webview2'?'WEBVIEW2':'ELECTRON'),make('span',status(t)));c.append(top,make('b',t.title),make('small',t.url==='about:blank'?'about:blank':t.url));c.onclick=b.onclick;const cardWrap=make('div',undefined,'tab-card-wrap');const deleteCard=make('button','Delete tab','card-delete');deleteCard.disabled=!!t.busy;deleteCard.onclick=()=>invoke('close',{id:t.id});cardWrap.append(c,deleteCard);$('cards').append(cardWrap);}

 const t=s.tabs.find(t=>t.id===s.selected);$('home').hidden=!!t||s.section==='accounts';$('browser').hidden=!t||s.section==='accounts';$('accountsView').hidden=s.section!=='accounts';$('heading').textContent=s.section==='accounts'?'Accounts':t?t.title:'Overview';
 $('resourceTitle').textContent=t?t.title:'Shared browser';$('resourceState').textContent=t?status(t):s.paused?'Paused':'Idle';$('resourceOwner').textContent=t?.ownerLabel||'Unassigned';$('sessionId').textContent=t?.owner?.slice(0,8)||'None';$('cpu').textContent=`${(s.metrics?.cpu||0).toFixed(1)}%`;$('memory').textContent=`${s.metrics?.memoryMB||0} MB`;$('processes').textContent=s.metrics?.processes||0;
 $('control').disabled=!t||(!t.owner&&!t.error)||s.paused;$('release').disabled=!t?.owner||t.busy;$('control').textContent=t?.paused&&!t.error?'Return to agent':'Take control';
 $('controlHint').textContent=t?(t.busy&&(t.paused||s.paused)?'Current action is finishing. Input remains blocked.':t.owner&&!t.paused&&!s.paused?'Read-only preview. Take control to send input.':t.owner&&t.paused?'Finish your changes, then click Return to agent so the waiting task can continue.':'Direct browser input enabled. Cookies persist locally.'):'Select a tab to inspect input ownership.';
 $('release').hidden=false;$('resourceSessionLabel').textContent='Session';$('resourceStorage').textContent='Persistent';
 if(s.section==='accounts'){$('resourceTitle').textContent='Saved accounts';$('resourceState').textContent='Local vault';$('resourceOwner').textContent='You';$('sessionId').textContent='Not applicable';$('control').disabled=true;$('release').disabled=true;$('controlHint').textContent='Select a browser tab to inspect input control.';}
 if(t){if(document.activeElement!==$('address'))$('address').value=t.url==='about:blank'?'':t.url;const watching=t.owner&&!t.paused&&!s.paused;
  for(const id of ['back','forward','reload','address'])$(id).disabled=!!watching||t.busy;
  $('viewport').classList.toggle('executing',t.busy);$('preview').hidden=!watching&&!t.busy&&!t.error;$('watchLabel').hidden=!watching&&!t.busy;$('watchText').textContent=t.busy?`Executing: ${t.action||'navigation'}`:'Read-only preview. Refresh: 1000 ms';$('intervention').hidden=!t.error;$('failure').textContent=t.error||'';$('loading').hidden=!t.loading;
  if(previous!==s.selected){$('previewError').textContent='Loading live preview…';refreshPreview();$('viewport').animate([{opacity:.5},{opacity:1}],{duration:200,easing:'cubic-bezier(.25,.1,.25,1)'})}
 }
 renderSites();const blank=t?.url==='about:blank';$('tabStart').hidden=!blank;$('viewport').hidden=!!blank;$('savedLogins').disabled=!t||blank||t.busy||!!(t.owner&&!t.paused&&!s.paused);$('tabHistory').disabled=!t;updateLogs();
}
for(const id of ['newTab','sideNew','heroNew'])$(id).onclick=()=>invoke('new');
$('accountsNav').onclick=()=>invoke('accounts');
$('overview').onclick=()=>toggleWorkspace('workspace');$('collapse').onclick=()=>invoke('collapse');$('pauseAll').onclick=()=>invoke('pauseAll');$('downloads').onclick=()=>invoke('downloads');$('quit').onclick=()=>invoke('quit');
$('help').onclick=()=>$('settings').click();
$('control').onclick=()=>invoke('control',{id:state.selected});$('intervene').onclick=$('control').onclick;$('approve').onclick=()=>invoke('approve',{id:state.selected});$('release').onclick=()=>invoke('release',{id:state.selected});$('renameTab').onclick=()=>invoke('rename',{id:state.selected});$('closeTab').onclick=()=>invoke('close',{id:state.selected});
for(const a of ['back','forward','reload'])$(a).onclick=()=>invoke(a,{id:state.selected});
$('addressForm').onsubmit=e=>{e.preventDefault();let url=$('address').value.trim();if(!/^https?:\/\//i.test(url))url='https://'+url;invoke('navigate',{id:state.selected,url});};
$('switchEngine').onchange=async()=>{const b=$('switchEngine');b.disabled=true;try{const r=await invoke('setBackend',{backend:b.value});if(r)toast('Browser engine saved. Restart AS to apply.');else b.value=state.browserBackend||state.backend;}finally{b.disabled=false;}};
$('codexToggle').onclick=()=>invoke('codexSetup',{enabled:!state.codexStatus?.enabled||!!state.codexStatus?.error});
$('logFilter').oninput=updateLogs;$('logViewport').onscroll=renderLogs;new ResizeObserver(renderLogs).observe($('logViewport'));
$('cancelDelete').onclick=()=>invoke('cancelClose');$('deleteDialog').oncancel=e=>{e.preventDefault();invoke('cancelClose');};$('confirmDelete').onclick=async()=>{if(!state.pendingClose)return;const button=$('confirmDelete');button.disabled=true;try{await invoke('confirmClose',{id:state.pendingClose.id});}finally{button.disabled=false;}};
window.spaces.onState(render);invoke('state').then(s=>s&&render(s));
async function refreshPreview(){const t=state.tabs.find(t=>t.id===state.selected);if(state.section!=='workspace'||previewBusy||!t||(!t.owner&&!t.error)||((t.paused||state.paused)&&!t.busy&&!t.error))return;previewBusy=true;const id=t.id;try{const r=await window.spaces.invoke('preview',{id});if(state.selected!==id)return;if(!r?.image)throw Error('No image received');const next=new Image();next.src='data:image/png;base64,'+r.image;await next.decode();if(state.selected===id){$('preview').src=next.src;$('previewError').textContent='';}}catch(e){if(state.selected===id)$('previewError').textContent='Preview unavailable: '+e.message.replace(/^Error invoking remote method.*?Error: /,'');}finally{previewBusy=false;}}
setInterval(refreshPreview,1000);

let choiceVersion='';
function renderChoices(s){const v=JSON.stringify(s.accountRequests||[]);if(v===choiceVersion)return;choiceVersion=v;$('accountChoices').replaceChildren();for(const r of s.accountRequests||[]){const box=make('article',undefined,'account-card');box.append(make('h2','Which account should this task use?'),make('p',r.task+' · '+r.site));for(const o of r.options){const idParts=[];if(o.username)idParts.push(o.username);if(o.email&&o.email!==o.username)idParts.push(o.email);const b=make('button',idParts.join(' · ')+(o.label?' · '+o.label:''));b.onclick=()=>invoke('chooseAccount',{id:r.id,accountId:o.id});box.append(b);}const cancel=make('button','Cancel login');cancel.onclick=()=>invoke('chooseAccount',{id:r.id,accountId:null});box.append(cancel);$('accountChoices').append(box);}}
$('accountForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;const username=$('accountUsername').value.trim();const email=$('accountEmail').value.trim();if(!username&&!email){toast('Enter a username or email.');return;}b.disabled=true;try{const r=await invoke('saveAccount',{site:$('accountSite').value,username,email,password:$('accountPassword').value,label:$('accountLabel').value});if(r?.saved){$('accountForm').reset();toast('Account saved. Agents can request these login details.');}}finally{b.disabled=false;}};
function renderAccounts(s){renderChoices(s);$('accountsError').textContent=s.accountsError||'';const version=JSON.stringify(s.accounts||[]);if(version===accountVersion)return;accountVersion=version;$('accountRows').replaceChildren();if(!s.accounts?.length){$('accountRows').append(make('p','No accounts recorded yet. Supported successful signups and logins appear here automatically.'));return;}for(const a of s.accounts){const card=make('article',undefined,'account-card');const copyButton=(field,label)=>{const b=make('button',label);b.onclick=async()=>{b.disabled=true;try{const r=await invoke('copyAccountField',{id:a.id,field});if(r?.copied)toast(label.replace('Copy ','')+' copied');}finally{b.disabled=false;}};return b;};const idParts=[];for(const field of ['username','email'])if(a[field]){const row=make('div',undefined,'account-identity');row.append(make('p',a[field]),copyButton(field,'Copy '+field));idParts.push(row);}card.append(make('h2',a.site),make('span',a.source==='manual'?'Added manually':a.source==='agent'?'Agent created':a.source==='automatic'?'Saved automatically':'Created','tag'),...idParts,make('p','Task: '+a.task),make('small','Recorded '+new Date(a.createdAt).toLocaleString()),...(a.confirmedAt&&a.source!=='manual'?[make('small','Login verified '+new Date(a.confirmedAt).toLocaleString())]:[]),make('small','Task ID: '+a.taskId));const password=make('input');password.type='password';password.value='';password.placeholder='Password hidden';password.readOnly=true;password.setAttribute('aria-label','Password for '+(a.username||a.email||a.site));const reveal=make('button','Reveal password');let timeout;const hide=()=>{password.value='';password.type='password';reveal.textContent='Reveal password';};reveal.onclick=async()=>{if(password.value){clearTimeout(timeout);hide();return;}const r=await invoke('revealAccount',{id:a.id});if(r){password.type='text';password.value=r.password;reveal.textContent='Hide password';timeout=setTimeout(hide,15000);}};const defaultButton=make('label',undefined,'default-choice');const checkbox=make('input');checkbox.type='checkbox';checkbox.checked=!!a.isDefault;checkbox.onchange=async()=>{checkbox.disabled=true;const r=await invoke('setDefaultAccount',{id:a.id,enabled:checkbox.checked});if(!r)checkbox.checked=!!a.isDefault;checkbox.disabled=false;};defaultButton.append(checkbox,make('span',a.isDefault?'★ Default account':'Use as default'));const remove=make('button','Delete account','danger');remove.onclick=()=>{hide();invoke('deleteAccount',{id:a.id});};const credentials=make('div',undefined,'account-credentials');credentials.append(password,reveal,copyButton('password','Copy password'));const actions=make('div',undefined,'account-actions');actions.append(defaultButton,remove);card.append(credentials,actions);$('accountRows').append(card);}}

function renderDialogs(s){
 const r=s.pendingRename;
 if(r){if(!$('renameDialog').open){$('renameName').value=r.name;$('renameDialog').showModal();$('renameName').select();}}else if($('renameDialog').open)$('renameDialog').close();
 const login=s.saveRequests?.[0];
 if(login&&!r&&!s.pendingClose){$('saveLoginIdentity').textContent=login.username+' · '+login.site;if(!$('saveLoginDialog').open)$('saveLoginDialog').showModal();}else if($('saveLoginDialog').open)$('saveLoginDialog').close();

}

$('renameForm').onsubmit=async e=>{e.preventDefault();if(state.pendingRename)await invoke('confirmRename',{id:state.pendingRename.id,name:$('renameName').value});};
$('cancelRename').onclick=()=>invoke('cancelRename');$('renameDialog').oncancel=e=>{e.preventDefault();invoke('cancelRename');};
async function saveLoginChoice(save){const r=state.saveRequests?.[0];if(r)await invoke('accountSaveConsent',{id:r.id,save});}
$('declineLogin').onclick=()=>saveLoginChoice(false);$('acceptLogin').onclick=()=>saveLoginChoice(true);$('saveLoginDialog').oncancel=e=>{e.preventDefault();saveLoginChoice(false);};

$('settings').onclick=async()=>{await invoke('shellOverlay',{open:true});$('engineExplanation').hidden=true;$('engineInfo').setAttribute('aria-expanded','false');$('settingsDialog').showModal();};
$('settingsCancel').onclick=()=>$('settingsDialog').close();


$('engineInfo').onclick=()=>{$('engineExplanation').hidden=!$('engineExplanation').hidden;$('engineInfo').setAttribute('aria-expanded',String(!$('engineExplanation').hidden));};
$('confirmDeleteHistory').onclick=async()=>{const p=state.pendingClose;if(!p||p.kind==='account')return;$('confirmDeleteHistory').disabled=true;try{await invoke('confirmClose',{id:p.id,deleteHistory:true});}finally{$('confirmDeleteHistory').disabled=false;}};
function renderSites(){for(const id of ['popularSites','tabSites']){const box=$(id);box.replaceChildren();if(!(state.popularSites||[]).length){box.append(make('p','Frequently visited sites will appear here.'));continue;}for(const site of state.popularSites){const b=make('button',site.domain);b.onclick=()=>id==='tabSites'?invoke('navigate',{id:state.selected,url:site.url}):invoke('new',{url:site.url});box.append(b);}}}
let historyTab=null,historyGeneration=0;
async function loadHistory(){const generation=++historyGeneration;const r=await invoke('browserHistory',{tabId:historyTab,query:$('historySearch').value});if(!r||generation!==historyGeneration)return;$('historyRows').replaceChildren();const groups=new Map();for(const row of r.rows){if(!groups.has(row.tabId))groups.set(row.tabId,[]);groups.get(row.tabId).push(row);}for(const [id,rows] of groups){const tab=state.tabs.find(t=>t.id===id),card=make('article');card.append(make('strong',tab?.title||'Closed tab'),make('small',' · '+id));for(const row of rows)card.append(make('p',new Date(row.at).toLocaleString()+' · '+row.actor+' · '+row.action+' · '+row.outcome+' · '+(row.site||'Blank page')+' · '+(row.engine||'')));if(tab){const b=make('button','Open tab');b.onclick=()=>{$('historyDialog').close();invoke('select',{id});};card.append(b);}else{const b=make('button','Delete this tab’s history');b.onclick=()=>{b.replaceWith(make('span','Remove all saved events for this closed tab? '));const yes=make('button','Delete history'),no=make('button','Cancel');yes.onclick=async()=>{await invoke('deleteHistory',{tabId:id});loadHistory();};no.onclick=()=>loadHistory();card.append(yes,no);};card.append(b);}$('historyRows').append(card);}if(!r.rows.length)$('historyRows').append(make('p','No matching history.'));}
async function openHistory(tabId=null){historyTab=tabId;$('historySearch').value='';$('historyTitle').textContent=tabId?'History for this tab':'Browser history';await invoke('shellOverlay',{open:true});$('historyDialog').showModal();await loadHistory();}
$('historyNav').onclick=()=>openHistory();$('tabHistory').onclick=()=>openHistory(state.selected);$('historyClose').onclick=()=>$('historyDialog').close();$('historySearch').oninput=loadHistory;$('historyFile').onclick=()=>invoke('openHistoryFile');
$('savedLogins').onclick=async()=>{const id=state.selected;const r=await invoke('manualAccounts',{id});if(!r)return;await invoke('shellOverlay',{open:true});$('loginPickerSite').textContent=r.origin;$('loginPickerRows').replaceChildren();for(const a of r.accounts.sort((a,b)=>Number(b.isDefault)-Number(a.isDefault))){const b=make('button',(a.isDefault?'★ Default · ':'')+(a.username||a.email)+' · '+a.site);b.onclick=async()=>{b.disabled=true;const done=await invoke('fillSavedAccount',{id,accountId:a.id,origin:r.origin});if(done){$('loginPicker').close();toast('Login filled. Review it, then submit when ready.');}b.disabled=false;};$('loginPickerRows').append(b);}if(!r.accounts.length)$('loginPickerRows').append(make('p','No saved accounts match this site. Add one in Accounts.'));$('loginPicker').showModal();};
$('loginPickerClose').onclick=()=>$('loginPicker').close();
// Native browser surfaces must stay behind shell dialogs, including Settings and History.
const dialogVisibility=new MutationObserver(()=>invoke('shellOverlay',{open:!!document.querySelector('dialog[open]')}));for(const d of document.querySelectorAll('dialog'))dialogVisibility.observe(d,{attributes:true,attributeFilter:['open']});

$('pauseInfo').onclick=async()=>{await invoke('shellOverlay',{open:true});$('pauseInfoDialog').showModal();};$('pauseInfoClose').onclick=()=>$('pauseInfoDialog').close();

let expandedWorkspace=true;
function renderSidebar(s){$('browserChildren').hidden=!expandedWorkspace;$('overview').setAttribute('aria-expanded',String(expandedWorkspace));$('overview').setAttribute('aria-controls','browserChildren');}
function toggleWorkspace(){if(state.section==='workspace'){expandedWorkspace=!expandedWorkspace;renderSidebar(state);}else{expandedWorkspace=true;invoke('select',{id:null});}}
